### ISSUE TITLE
GitHub page Demo

### ISSUE THREAD

**Issue by olawalejuwonm** [LD239/WebTranscript#1]
Got this error on console

![image](https://github.com/LD239/WebTranscript/assets/52759812/dc77a22e-e176-4564-b75f-e3a696f89d1f)

**Comment by dimarvino** [comment]
Did you follow the steps in the README and install the system locally, or did you try to process a new video on the static GitHub page? Please note that the GitHub page is only for demonstrating the user interface. Since the processing happens on the backend, the server needs to be installed locally.

If you encounter any issues during the installation, I'm happy to help you.

**Comment by LD239** [comment]
Did you follow the steps in the README and install the system locally, or did you try to process a new video on the static GitHub page? Please note that the GitHub page is only for demonstrating the user interface. Since the processing happens on the backend, the server needs to be installed locally. If you encounter any issues during the installation, I'm happy to help you. 

If you encounter any issues during the installation, I'm happy to help you.

**Comment by olawalejuwonm** [comment]
No not installed locally.

**Comment by LD239** [comment]
Okay, could you try installing it when you have time? I'd appreciate any feedback you can give me.

**Comment by LD239** [comment]
If you need help with the installation, please open a new ticket.
